# Generated by Django 3.2.6 on 2021-08-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210819_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Набор фото', 'verbose_name_plural': 'Наборы фоток'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='photoset',
        ),
        migrations.DeleteModel(
            name='Photoset',
        ),
    ]
