# Generated by Django 3.2.6 on 2021-08-21 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210821_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Страна производитель', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='main.product'),
        ),
    ]
