# Generated by Django 3.2.6 on 2021-08-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_photo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'We got your order!'), (2, 'We have packaged your items and have handed your package to our trusted carriers. '), (3, 'Delivered')], default=1, verbose_name='Статус'),
        ),
    ]
