# Generated by Django 3.2.6 on 2021-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cdek_uuid',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='CDEK UUID'),
        ),
    ]
